pretrained_path: /work/21013187/SAM-SLR-v2/videomae-base-finetuned_with_landmark/checkpoint-4886

train:
  num_epochs: 5
  learning_rate: 0.000005
  

dataset:
    dataset_root_path: /work/21013187/SAM-SLR-v2/data/rgb
    batch_size: 15

landmark:
  use: True
  use_gcn: True
  fusion: lately # [early,lately] 
  num_keypoints: 81 # 27 keypoints * 3 x,y,z locations


   
