pretrained_path: /work/21013187/SAM-SLR-v2/phuoc_src/weights/checkpoint-4886-finetuned/checkpoint-1677

train:
  num_epochs: 10
  learning_rate: 0.000005
  

dataset:
    dataset_root_path: /work/21013187/SAM-SLR-v2/data1
    batch_size: 3

landmark:
  use: False
  use_landmark_transformers: True
  fusion: early # [early,lately] 
  num_keypoints: 81 # 27 keypoints * 3 x,y,z locations
  num_heads: 8 
  num_layers: 4
  max_len: 128
  dropout: 0.1

depth:
  use: False

   
